# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Labmems/Desktop/David Eduardo/Proy_Final/Proy_Final.srcs/sources_1/ip/clk_wiz_100/clk_wiz_100.xci
# IP: The module: 'clk_wiz_100' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Labmems/Desktop/David Eduardo/Proy_Final/Proy_Final.srcs/sources_1/ip/clk_wiz_100/clk_wiz_100_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Labmems/Desktop/David Eduardo/Proy_Final/Proy_Final.srcs/sources_1/ip/clk_wiz_100/clk_wiz_100.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Labmems/Desktop/David Eduardo/Proy_Final/Proy_Final.srcs/sources_1/ip/clk_wiz_100/clk_wiz_100_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Labmems/Desktop/David Eduardo/Proy_Final/Proy_Final.srcs/sources_1/ip/clk_wiz_100/clk_wiz_100.xci
# IP: The module: 'clk_wiz_100' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Labmems/Desktop/David Eduardo/Proy_Final/Proy_Final.srcs/sources_1/ip/clk_wiz_100/clk_wiz_100_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Labmems/Desktop/David Eduardo/Proy_Final/Proy_Final.srcs/sources_1/ip/clk_wiz_100/clk_wiz_100.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Labmems/Desktop/David Eduardo/Proy_Final/Proy_Final.srcs/sources_1/ip/clk_wiz_100/clk_wiz_100_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
